# Generated by Django 5.0.3 on 2024-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('edificio', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('hora_reserva', models.TimeField(blank=True, null=True)),
                ('hora_devolucion', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
