# Generated by Django 5.0.3 on 2024-04-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_implemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implemento_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implemento', models.CharField(max_length=100)),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('edificio', models.CharField(max_length=100)),
                ('disponibilidad', models.CharField(choices=[('D', 'Disponible'), ('ER', 'En reserva'), ('ND', 'No disponible')], max_length=2)),
                ('hora_reserva', models.DateTimeField(blank=True, null=True)),
                ('hora_max_reserva_devolucion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Implemento',
        ),
    ]
