# Generated by Django 5.0.3 on 2024-04-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_implemento_1_delete_implemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implemento_1',
            name='disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En reserva', 'En reserva'), ('No disponible', 'No disponible')], max_length=13),
        ),
        migrations.AlterField(
            model_name='implemento_1',
            name='hora_max_reserva_devolucion',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='implemento_1',
            name='hora_reserva',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
