# Generated by Django 5.0.3 on 2024-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_alter_implemento_1_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento_1',
            name='hora_confirmacion_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
