# Generated by Django 5.0.3 on 2024-04-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_implemento_1_hora_confirmacion_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implemento_1',
            name='hora_confirmacion_reserva',
        ),
        migrations.AddField(
            model_name='implemento_1',
            name='reserva_confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
